### ISSUE TITLE
Add piping support

### ISSUE THREAD

**Issue by zntfdr** [lordcodes/imagecram#13]
I'd like to know if there's any interest in having <kbd>imagecram</kbd> support command line piping.

My main use case is to use imagecram in the following way:

```cli
$ git status -s "*.png" | awk '{print $2}' | imagecram
```

This pipe automatically finds all the uncommitted image files in a repository and then feed them to <kbd>imagecram</kbd>.

This is just an example, but there are many other similar use cases.

## Solution

There are essentially two main ways to do this:

### 1. The automatic way

in <kbd>main.swift</kbd> we check whether there's any data in the standard input buffer and, if there is, we parse it and feed it to 
 `ImageCramCommand`'s [`main(_:)`](https://github.com/apple/swift-argument-parser/blob/f314199a3db41cc7d421b1d6d409a35cd0a237ed/Sources/ArgumentParser/Parsable%20Types/ParsableCommand.swift#L92).

I have a working implementation of this in [my <kbd>stream-input</kbd> branch](https://github.com/zntfdr/imagecram/tree/stream-input), you can see all the changes in [this](https://github.com/zntfdr/imagecram/commit/d0bbd4989b678f7658daefafa06747627d9c5cfd) commit.

### 2. The flag way (similar to [SwiftLint](https://github.com/realm/SwiftLint/blob/5a98458d94d623ba7ea1a86769aa7685d4fc86f8/Source/swiftlint/Commands/Lint.swift#L12))

We introduce a new `@Flag` telling `ImageCramCommand` to use the standard input instead of reading the `inputs` `@Argument`.

Please let me know what you think! If there's interest, I'd be happy to send a PR for this :)

## Checklist

- [x] I've read the [guide for contributing](https://github.com/lordcodes/imagecram/blob/master/CONTRIBUTING.md).
- [x] I've checked there are no other [open pull requests](https://github.com/lordcodes/imagecram/pulls) for the feature.
- [x] I've checked there are no other [open issues](https://github.com/lordcodes/imagecram/issues) for the same feature.

## Additional context

Thank you very much for building this very handy tool ❤️

**Comment by lordcodes** [comment]
Thanks, really glad someone is using the tool and finds it helpful!

This feature sounds like a great idea, I like the 'automatic' way from above, it seems intuitive, what I would expect and works like other standard system tools.
